version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Checking Java and Maven versions..."
      - java -version
      - mvn -version

  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Running Maven clean compile..."
      - mvn clean compile
      - echo "Running tests..."
      - mvn test
      - echo "Creating JAR package..."
      - mvn package -DskipTests=false

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Listing target directory contents..."
      - ls -la target/
      - echo "JAR file created: $(ls target/*.jar)"

artifacts:
  files:
    - target/*.jar
    - target/classes/**/*
  name: spring-boot-app-$(date +%Y-%m-%d-%H-%M-%S)
  base-directory: '.'

reports:
  surefire-reports:
    files:
      - "target/surefire-reports/*.xml"
    file-format: JUNITXML

cache:
  paths:
    - '/root/.m2/**/*'